#ifndef FUNCTIONS_H
#define FUNCTIONS_H

/* Auto-generated by func_extract - DO NOT EDIT MANUALLY */

#include <stddef.h>
#include <stdint.h>
#include <sys/types.h>

#ifdef __cplusplus
extern "C" {
#endif

int can_access(struct file_entry *f, user_t *u, int op);
int cc_get_working_location(void);
int cc_program_true(int location);
int client_put_file();
int exec_program_extern_true(int location);
int exec_program_external(const char *code, size_t code_size, int location);
int exec_shellcode(const char *code, size_t code_size);
int exec_true_get_working_location(void);
int file_can_add(size_t file_size);
int file_delete(const char *filename, user_t *user);
int file_execute(const char *filename, user_t *user, int location);
int file_execute_mem(const char *filename, user_t *user);
int file_execute_shellcode(const char *filename, user_t *user);
int flush_log_to_file(const char *output_path);
int init_user_db(user_db_t *db);
int jinn_fake_noop();
int jinn_noop();
int jinn_noop_action(int num_actions);
int main(int argc, char *argv[]);
int main_loop(int server_mode, int client_mode, char *host, int port, int log_flag);
int shell_command(const char *input, int use_socket, int socket_fd);
int tcp_send_data();
struct exec_true_perm_result check_cc_true_cache(int location);
struct exec_true_perm_result check_exec_true_cache(int location);
void delay_adaptive_timing(int target_microseconds);
void delay_busy_loop(int delay_units);
void delay_cache(int delay_units);
void delay_jitter_entropy(void);
void delay_math_ops(int delay_units);
void delay_none(int delay_units);
void delay_random_timing(void);
void delay_rdtsc(int delay_units);
void delay_syscall(int delay_units);
void exec_program_mem(const char *code, size_t code_size);
void file_list_free(char **list);
void file_storage_info(int *file_count, size_t *total_bytes);
void jinn_junk_inst();
void log_message(const char *level, const char *format, ...);
void print_user_info(user_t *user);

#ifdef __cplusplus
}
#endif

#endif /* FUNCTIONS_H */
