#ifndef FUNCTIONS_H
#define FUNCTIONS_H

/* Auto-generated by extract_functions.py - DO NOT EDIT MANUALLY */

#ifdef __cplusplus
extern "C" {
#endif

const char* magic8ball(void);
int check_if_watched();
int client_get_file();
int client_put_file();
int data_store_perm();
int mem_alloc_add_file();
int mem_alloc_del_file();
int mem_alloc_fs();
int mem_alloc_fs_free();
int mem_set_exec();
int mem_set_nexec();
int pipe_recv_data();
int pipe_send_data();
int pipe_setup();
int tcp_recv_data();
int tcp_send_data();
int user_adduser();
int user_auth_user();
int user_deluser();
int user_set_perm();

#ifdef __cplusplus
}
#endif

#endif /* FUNCTIONS_H */
